# Generated by Django 2.2.3 on 2019-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='manifacturing_date',
            new_name='manufacturing_date',
        ),
        migrations.AlterField(
            model_name='dronecategory',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
