# Generated by Django 2.2.3 on 2019-07-27 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_drone_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='drone_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drones1', to='drones.DroneCategory'),
        ),
    ]
